# Generated by Django 5.2.1 on 2025-05-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name server')),
                ('alert_time', models.TimeField(verbose_name='Time alert')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push-message')], max_length=10, verbose_name='Type alert')),
                ('email', models.EmailField(max_length=254, verbose_name='Email adress')),
                ('server_group', models.CharField(max_length=100, verbose_name='Servers group')),
                ('server_group_type', models.CharField(verbose_name='Type group servers')),
                ('location', models.CharField(max_length=200, verbose_name='Location server')),
            ],
        ),
    ]
